---
# tasks file for wp-install

- name: Update packeges
  apt: name=* state=latest

- name: Install apache2
  apt: name=apache2 state=latest

- name: Install ghostscript
  apt: name=ghostscript state=latest

- name: Install libapache2-mod-php
  apt: name=libapache2-mod-php state=latest

- name: Install mysql-server
  apt: name=mysql-server state=latest

- name: Install php
  apt: name=php state=latest

- name: Install php-bcmath
  apt: name=php-bcmath state=latest

- name: Install php-curl
  apt: name=php-curl state=latest

- name: Install php-imagick
  apt: name=php-imagick state=latest

- name: Install php-intl
  apt: name=php-intl state=latest

- name: Install php-json
  apt: name=php-json state=latest

- name: Install php-mbstring
  apt: name=php-mbstring state=latest

- name: Install php-mysql
  apt: name=php-mysql state=latest

- name: Install php-xml
  apt: name=php-xml state=latest

- name: Install php-zip
  apt: name=php-zip state=latest

- name: Install PIP
  apt: name=pip state=latest

- name: Install PyMySQL
  pip: name=pymysql state=present 

- name: Making Directory of Wordpress
  shell: mkdir -p /var/www/
  
- name: Changing Owner
  shell: chown www-data:www-data /var/www/
   
- name: Get and Install WP
  shell: curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /var/www

- name: Set Access to Folder
  shell: chmod 755 /var/www/wordpress

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/wordpress.key

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/certs/wordpress.crt
    privatekey_path: /etc/ssl/private/wordpress.key
    provider: selfsigned

- block:

  - name: Writing IP adress to the etc/hosts file
    shell: echo 192.168.31.251 www.one.wordpress.ru one.wordpress.ru >> /etc/hosts 

  - name: Create WordPress Config File
    template: src=wordpress.j2 dest={{ destin_folder_a2 }}/wordpress.conf mode=0644
    vars:
      servername: one.wordpress.ru
      redirect: https://one.wordpress.ru

  - name: Create SSL WordPress Config File
    template: src=ssl-wordpress.j2 dest={{ destin_folder_a2 }}/ssl-wordpress.conf mode=0644
    vars:
      servername: one.wordpress.ru

  when: ansible_all_ipv4_addresses == ['192.168.31.251']

- block:

  - name: Writing IP adress to the etc/hosts file
    shell: echo 192.168.31.121 www.two.wordpress.ru two.wordpress.ru >> /etc/hosts

  - name: Create WordPress Config File
    template: src=wordpress.j2 dest={{ destin_folder_a2 }}/wordpress.conf mode=0644
    vars:
      servername: two.wordpress.ru
      redirect: https://two.wordpress.ru

  - name: Create SSL WordPress Config File
    template: src=ssl-wordpress.j2 dest={{ destin_folder_a2 }}/ssl-wordpress.conf mode=0644
    vars:
      servername: two.wordpress.ru

  when: ansible_all_ipv4_addresses == ['192.168.31.121']


- name: Enable the site
  shell: sudo a2ensite wordpress

- name: Enable URL rewrite
  shell: sudo a2enmod rewrite

- name: Disable the default “It Works” site
  shell: sudo a2dissite 000-default

- name: Activate SSL config
  shell: sudo a2ensite ssl-wordpress.conf

- name: Activate SSL_MOD
  shell:  sudo a2enmod ssl

- name: Apache2 Start
  service: name=apache2 state=started



- block:

  - name: Create Mysql File to Server1
    template: src=mysql.j2 dest={{ destin_folder_mysql }}/mysql.txt mode=0644
    vars:
      database: SuperData
      user: Johny
      passwrd: 1111

  - name: MySQL 
    shell: sudo mysql -u root < /home/boris/mysql.txt

  - name: Configure WordPress to connect to the database
    shell: sudo -u www-data cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
  - name: Change DB Name
    shell: sudo -u www-data sed -i 's/database_name_here/SuperData/' /var/www/wordpress/wp-config.php
  - name: Change User Name
    shell: sudo -u www-data sed -i 's/username_here/Johny/' /var/www/wordpress/wp-config.php

  - name: Change Password
    shell: sudo -u www-data sed -i 's/password_here/1111/' /var/www/wordpress/wp-config.php


  when: ansible_all_ipv4_addresses == ['192.168.31.251']

- block:

  - name: Create Mysql File to Server2
    template: src=mysql.j2 dest={{ destin_folder_mysql }}/mysql.txt mode=0644
    vars:
      database: PuperData
      user: Ivan
      passwrd: 2222

  - name: MySQL
    shell: sudo mysql -u root < /home/boris/mysql.txt

  - name: Configure WordPress to connect to the database
    shell: sudo -u www-data cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php

  - name: Change DB Name
    shell: sudo -u www-data sed -i 's/database_name_here/PuperData/' /var/www/wordpress/wp-config.php

  - name: Change User Name
    shell: sudo -u www-data sed -i 's/username_here/Ivan/' /var/www/wordpress/wp-config.php

  - name: Change Password
    shell: sudo -u www-data sed -i 's/password_here/2222/' /var/www/wordpress/wp-config.php

  when: ansible_all_ipv4_addresses == ['192.168.31.121']

- name: Delete Strings from WP Config.php
  shell: sudo sed '51,$d' /var/www/wordpress/wp-config.php > /var/www/wordpress/wp-config_dop.php

- name: Copy Dop_File to Server
  copy: src={{ source_file_dop }} dest={{ destin_folder_dop }} mode=0644

- name: Rename Config File
  shell: sudo rm  /var/www/wordpress/wp-config.php

- name: Union of Two Files WP Config
  shell: cat /var/www/wordpress/wp-config_dop.php /home/boris/dop_file.txt > /var/www/wordpress/wp-config.php

- name: Delete WP-Config_dop.php
  shell: sudo rm /var/www/wordpress/wp-config_dop.php

- name: Apache2 Restart
  service: name=apache2 state=restarted
